use reqwest::Client;
use serde::Serialize;
use std::env;

#[derive(Serialize)]
struct EmailPayload {
    sender: Sender,
    to: Vec<Recipient>,
    subject: String,
    #[serde(rename = "textContent")]
    text_content: String,
    #[serde(rename = "htmlContent")]
    html_content: String,
}

#[derive(Serialize)]
struct Sender {
    name: String,
    email: String,
}

#[derive(Serialize)]
struct Recipient {
    email: String,
}

pub async fn send_email(recipient: &str, subject: &str, body: &str) -> Result<(), anyhow::Error> {
    let api_key = env::var("SMTP_API_KEY").expect("BREVO_API_KEY must be set");
    let client = Client::new();

    let html = generate_html_alert("Monitor Alert", subject, body, None);

    let payload = EmailPayload {
        sender: Sender {
            name: "Plethora Monitor".to_string(),
            email: "plethora.onchain@gmail.com".to_string(),
        },
        to: vec![Recipient {
            email: recipient.to_string(),
        }],
        subject: subject.to_string(),
        text_content: body.to_string(),
        html_content: html,
    };

    let response = client
        .post("https://api.brevo.com/v3/smtp/email")
        .header("api-key", api_key)
        .header("content-type", "application/json")
        .json(&payload)
        .send()
        .await?;

    if response.status().is_success() {
        println!("Email sent via API to {}", recipient);
    } else {
        let error_text = response.text().await?;
        eprintln!("❌ Brevo API Error: {}", error_text);
    }

    Ok(())
}

/// Helper functions to display emails in html format

pub fn generate_html_alert(source: &str, title: &str, details: &str, link: Option<&str>) -> String {
    format!(
        r##"
<!DOCTYPE html>
<html>
<head>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f4f4f7; margin: 0; padding: 0; }}
    .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
    .card {{ background: #ffffff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); overflow: hidden; }}
    .header {{ background: #1a1a1a; color: #ffffff; padding: 20px; text-align: center; }}
    .header h1 {{ margin: 0; font-size: 24px; }}
    .content {{ padding: 30px; }}
    .alert-badge {{ display: inline-block; background: #e53e3e; color: white; padding: 4px 12px; border-radius: 99px; font-size: 12px; font-weight: bold; text-transform: uppercase; margin-bottom: 10px; }}
    .data-table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
    .data-table td {{ padding: 10px 0; border-bottom: 1px solid #eee; vertical-align: top; }}
    .label {{ color: #666; font-weight: 600; width: 30%; }}
    .value {{ font-family: 'Courier New', monospace; color: #1a1a1a; word-break: break-all; }}
    .btn {{ display: block; width: 100%; text-align: center; background: #2563eb; color: #ffffff; padding: 12px; border-radius: 6px; text-decoration: none; font-weight: bold; margin-top: 20px; }}
    .footer {{ text-align: center; padding: 20px; color: #999; font-size: 12px; }}
  </style>
</head>
<body>
  <div class="container">
    <div class="card">
      <div class="header">
        <h1>Plethora Monitor</h1>
      </div>
      <div class="content">
        <span class="alert-badge">Alert Triggered</span>
        <h2 style="margin-top: 0;">{source}</h2>
        <p style="color: #666;">{title}</p>

        <table class="data-table">
          {details_rows}
        </table>

        {button_html}
      </div>
    </div>
    <div class="footer">
      Generated by Plethora Monitor • <a href="#" style="color: #999;">Unsubscribe</a>
    </div>
  </div>
</body>
</html>
"##,
        source = source,
        title = title,
        details_rows = format_details_to_rows(details),
        button_html = if let Some(url) = link {
            format!(r#"<a href="{}" class="btn">View on Explorer</a>"#, url)
        } else {
            String::new()
        }
    )
}

// Helper to display emails in html table format
fn format_details_to_rows(raw_text: &str) -> String {
    raw_text
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| {
            if let Some((key, val)) = line.split_once(':') {
                format!(
                    r#"<tr><td class="label">{}</td><td class="value">{}</td></tr>"#,
                    key.trim(),
                    val.trim()
                )
            } else {
                format!(r#"<tr><td colspan="2" class="value">{}</td></tr>"#, line)
            }
        })
        .collect()
}
