# name of the workflow
name: Rust

# run workflow when the condition is met
on:
  # run when code is pushed on the `main` branch
  push:
    branches: ["main"]
  # run when a pull request to the `main` branch
  pull_request:
    branches: ["main"]

# env variables
env:
  CARGO_TERM_COLOR: always

# jobs
jobs:
  # job name
  deploy:
    # os to run the job on
    runs-on: ubuntu-latest
    # steps for job
    steps:
      # this will get the code and set the git
      - uses: actions/checkout@v3

      # heroku deployment
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          # key from repository secrets
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # name of the Heroku app
          heroku_app_name: "pl-monitor"
          # email from which the app is uploaded
          heroku_email: "jowoloko@gmail.com"
          # Use Rust buildpack - Heroku will compile the code
          buildpack: "https://github.com/emk/heroku-buildpack-rust.git"
